### ISSUE TITLE
Rewards Using WRONG count... and monthly votes reset themselves???

### ISSUE THREAD

**Issue by mrcoffee1026** [teozfrank/UltimateVotes#14] opened 2017-11-02 19:35 UTC
Hadn't been making use of the monthly vote counts at all up to now... kind of neglected to do anything with them.  Noticed someone get a promotion for 6 votes... after having accumulated 178 total... realized that the monthly vote had reset to 0 for everyone without my calling the command AND that rewards are being given out based on MONTHLY vote counts instead of GLOBAL vote count as it should be.  Help!

**Comment by teozfrank** [comment] 2017-11-02 20:53
> rewards are being given out based on MONTHLY vote counts instead of GLOBAL vote count as it should be.

Sorry but no rewards are given out based on the MONTHLY votes vote count, this is the way it is and ever has been since the plugin had been released 3 years ago this is NOT a bug its actually how the plugin operates. 

There is though an update which allows you to change what table is used for the cumulative based rewards which should be released soon (I have someone testing it live on a server at the moment). You will not be able to change this until this update comes out.

**Comment by mrcoffee1026** [comment] 2017-11-02 20:58
"no rewards are given out based on the MONTHLY votes vote count" -- a reward was just given out based on the monthly vote count, that's why I'm reporting this as an issue.  I don't see any value of doing.  Having a recurring reward every month would be a nice feature to have in this plugin, but I do not believe this should be the default behavior, it that IS the default behavior, this feature should be better documented as it seems to suggest that rewards are only given out on TOTAL count, not monthly count, which they clearly are.

**Comment by teozfrank** [comment] 2017-11-02 21:11
> it that IS the default behavior, this feature should be better documented as it seems to suggest that rewards are only given out on TOTAL count, not monthly count, which they clearly are.

That is the default behaviour and has always been that way, you are the second person whom reported this as a "problem" (the first person requested a new feature to which he is testing at the moment) the second out of over **394 buyers**, so are you saying these 392 buyers should have assumed it was based on the TOTAL count? sorry but I dont think so these other buyers assumed that it was based on the MONTHLY votes to of which I did not document as I thought this was the normal way users wanted. 

You could have just said hey I noticed the plugin rewards on monthly votes is that right? Could you make it work to allvotes instead? and I could have said yes sure there is an update for that soon instead of making it out that it was my fault that you assumed wrong instead of asking me. I guess you were frustrated but not to worry I'll try have this update out as soon as possible so you can use the plugin the way you assumed! Next time just ask! :)

PS. Monthly votes reset every month, why? If they didnt reset they wouldnt be monthly votes!

**Comment by mrcoffee1026** [comment] 2017-11-02 21:24
There's a few issues with resetting without any input from the end user: for one thing I can't very well have a monthly vote contest since the number will get reset without my getting a chance to look at them.  I can therefore issue no rewards as a result.  As there is a command to manually reset the votes, it would seem that this doesn't happen on its own.  Also, for the last 2+ months it did not automatically reset.  Assuming that the system rewards based on monthly votes... really makes no sense to me.  Options are very limited by way of voting plugins lately, this is one of the few remaining that seems even capable of keeping a count, so money well spent even if I misunderstood, but having it default to recurring rewards would still be... as I said - a nice feature - but not one that I would have expected to be default behavior.  No other vote plugin does this, and far fewer mention any sort of recurring ability.  That yours does should be a selling point... that it is mentioned exactly no where... is not an oversight on my part.  Anyway thanks for the time, I guess.

**Comment by teozfrank** [comment] 2017-11-02 21:43
> There's a few issues with resetting without any input from the end user: for one thing I can't very well have a monthly vote contest since the number will get reset without my getting a chance to look at them. 

I see, part of the new update also records the top X monthly voters in a seperate table to which you can look up to see who was in the top voters (before this was actually stored in a flat file)

> it would seem that this doesn't happen on its own. Also, for the last 2+ months it did not automatically reset. 

Correct, it is automated. Ok how often does your server restart?

 

> No other vote plugin does this, and far fewer mention any sort of recurring ability. That yours does should be a selling point... that it is mentioned exactly no where... is not an oversight on my part. 

I agree the documentation should be updated to reflect this to which I will do now. Thanks.

**Comment by teozfrank** [comment] 2017-11-02 21:46
Speaking of which see below:

> Cumulitive rewards that are given to players when they reach a certain amount of **votes in a month**. These can either be world specific or not.

Even though it is not said outright it does mention that its in a month that cumulative rewards are based on the rewards section of the wiki in case you missed that.

**Comment by mrcoffee1026** [comment] 2017-11-03 00:39
Yeah I did miss that.  I do appreciate the clarification and look forward to the next versions added features.  My server restarts... about once a week often more often?  I run things like spigot updates about once a week or so.  Since I've put the plugin on about 3 months ago, this was the first time it reset (on its own without me asking for it), partly why I was so confused (it's suddenly behaving in ways it had not previously).  If it's supposed to auto-reset every month then... it's not very consistent about it.  And ... AHA... YES.. I DO see the flat file you're talking about.  Just... this is the first time it generated data in it I guess?  It would be cool if that could be further customized like up to the top 10 for the last month... if you're storing it in a DB table in the next release I guess it might be easier to poll more or less whatever out of there.

Temporarily - in the mean time - until I get the option to use the total over monthly... I've just copied the total data into the monthly table since my rewards were for things like vote rank... having the counts reset are... well... it breaks everything.  If I alter the data in the "last reset" table to something like a year from now... would it stop resetting entirely?  If not I can just plan on copying the table data once a month.. or however often resets happen for me from this point on... until your next release.

Thanks again.

**Comment by teozfrank** [comment] 2017-11-26 19:51
> Yeah I did miss that. I do appreciate the clarification and look forward to the next versions added features. My server restarts... about once a week often more often? I run things like spigot updates about once a week or so. Since I've put the plugin on about 3 months ago, this was the first time it reset (on its own without me asking for it), partly why I was so confused (it's suddenly behaving in ways it had not previously). If it's supposed to auto-reset every month then... it's not very consistent about it. And ... AHA... YES.. I DO see the flat file you're talking about. Just... this is the first time it generated data in it I guess? It would be cool if that could be further customized like up to the top 10 for the last month... if you're storing it in a DB table in the next release I guess it might be easier to poll more or less whatever out of there.

I have released a new update which implements both of these. By the way the plugin only checks for new months on startup so since you didnt restart your server in quite some time then it won't auto reset. I was going on the assumption that server owners would restart at least once a day. I will have to add a task to check for new days in a future update so its not relying on restarts.

I will close this issue as its no longer relivant.

**Closed as completed** 2017-11-26 19:53 UTC
Labels: invalid
